FROM golang:1.10.1-alpine3.7

# Add build tools
RUN apk update && \
    apk add --no-cache git gcc musl-dev mercurial && \
    wget -O dep-install.sh https://raw.githubusercontent.com/golang/dep/master/install.sh && \
    sh dep-install.sh

WORKDIR /bin

